In [1]:
import pandas as pd

In [2]:
stellar_data = pd.read_csv('STELLARHOSTS.csv')
planetary_data = pd.read_csv('planetary_data.csv')
atmos_data = pd.read_csv('atmo_spec.csv')
atmos_data2 = pd.read_csv('atmo_spec2.csv')

In [3]:
print("Planetary Data Description:")
print(planetary_data.describe())

print("\nStellar Data Description:")
print(stellar_data.describe())

print(stellar_data.head())

Planetary Data Description:
          loc_rowid  default_flag       sy_snum       sy_pnum     disc_year  \
count  36482.000000  36482.000000  36482.000000  36482.000000  36482.000000
mean   18241.500000      0.158571      1.086042      1.884244   2015.410312
std    10531.590597      0.365281      0.310666      1.205737      3.901016
min        1.000000      0.000000      1.000000      1.000000   1992.000000
25%     9121.250000      0.000000      1.000000      1.000000   2014.000000
50%    18241.500000      0.000000      1.000000      1.000000   2016.000000
75%    27361.750000      0.000000      1.000000      2.000000   2016.000000
max    36482.000000      1.000000      4.000000      8.000000   2024.000000

       pl_controv_flag     pl_orbper    pl_orbsmax       pl_rade  \
count     36482.000000  3.330700e+04  20043.000000  24861.000000
mean          0.001974  1.310944e+04      5.011244      5.285868
std           0.044382  2.203994e+06    189.252364     69.348442
min           0.000000  9.070629e-02      0.004400      0.270000
25%           0.000000  4.361283e+00      0.054200      1.550000
50%           0.000000  1.033974e+01      0.100600      2.290000
75%           0.000000  2.667578e+01      0.220000      3.250000
max           1.000000  4.020000e+08  19000.000000   4282.980000

            pl_radj  ...        st_rad       st_mass        st_met  \
count  11748.000000  ...  33552.000000  30777.000000  22799.000000
mean       0.433705  ...      1.154041      0.943577     -0.026964
std        0.469017  ...      1.832567      0.330853      0.229490
min        0.025000  ...      0.010000      0.000000     -2.500000
25%        0.151000  ...      0.790000      0.810000     -0.160000
50%        0.227000  ...      0.950000      0.960000     -0.010000
75%        0.471250  ...      1.210000      1.070000      0.120000
max        8.102000  ...     88.470000     23.560000      7.790000

            st_logg            ra           dec       sy_dist       sy_vmag  \
count  29676.000000  36482.000000  36482.000000  35648.000000  35762.000000
mean       4.410908    263.238387     32.010267    731.198696     13.591066
std        0.296640     69.998005     27.692125    805.903494      2.432407
min        0.100000      0.185606    -88.121111      1.301190      0.872000
25%        4.310000    283.192078     38.343728    288.763000     12.595000
50%        4.470000    289.607943     42.640728    594.464000     14.204000
75%        4.570000    294.482877     46.640874    942.485000     15.283000
max        7.920000    359.974984     86.860343   8800.000000     45.340000

            sy_kmag    sy_gaiamag
count  35750.000000  35463.000000
mean      11.567807     13.356327
std        2.336033      2.368604
min       -3.044000      2.364310
25%       10.724000     12.379500
50%       12.287000     14.017100
75%       13.175000     15.056900
max       35.330000     20.186100

[8 rows x 27 columns]

Stellar Data Description:
         loc_rowid       sy_snum      sy_pnum       st_teff        st_rad  \
count  44974.00000  44974.000000  44974.00000  36849.000000  36234.000000
mean   22487.50000      1.111331      1.63430   5441.524870      1.265290
std    12983.01984      0.359786      1.03214    932.394689      2.604804
min        1.00000      1.000000      1.00000    415.000000      0.010000
25%    11244.25000      1.000000      1.00000   5052.000000      0.790000
50%    22487.50000      1.000000      1.00000   5592.000000      0.950000
75%    33730.75000      1.000000      2.00000   5936.000000      1.190000
max    44974.00000      4.000000      8.00000  57000.000000    109.460000

            st_mass        st_met       st_logg            ra           dec  \
count  27074.000000  21878.000000  30982.000000  44761.000000  44761.000000
mean       0.941213     -0.043260      4.418045    256.162456     28.900594
std        0.349447      0.246472      0.309050     77.099251     30.637570
min        0.000000     -2.551000      0.100000      0.184483    -88.121111
25%        0.800000     -0.180000      4.330000    274.405533     24.401656
50%        0.950000     -0.030000      4.470000    289.042243     42.166510
75%        1.070000      0.110000      4.570000    294.341607     46.449736
max       23.560000      7.790000      7.920000    359.974984     86.860343

            sy_dist       sy_vmag       sy_kmag    sy_gaiamag
count  43752.000000  44029.000000  43939.000000  43639.000000
mean     682.639960     13.110373     11.087451     12.894861
std      767.192501      2.975650      2.891961      2.909426
min        1.301190     -0.010000     -3.044000      2.364310
25%      202.943000     11.981000     10.128000     11.812700
50%      558.832500     14.058000     12.169000     13.889900
75%      930.457000     15.232000     13.150000     15.015100
max     8800.000000     45.340000     35.330000     20.916800
   loc_rowid sy_name hostname        tic_id  sy_snum  sy_pnum  \
0          1  11 Com   11 Com  TIC 72437047        2        1
1          2  11 Com   11 Com  TIC 72437047        2        1
2          3  11 Com   11 Com  TIC 72437047        2        1
3          4  11 Com   11 Com  TIC 72437047        2        1
4          5  11 Com   11 Com  TIC 72437047        2        1

                                          st_refname st_spectype  st_teff  \
0  <a refstr=KUNITOMO_ET_AL__2011 href=https://ui...         NaN      NaN
1  <a refstr=TENG_ET_AL__2023 href=https://ui.ads...      G8 III  4874.00
2  <a refstr=GAIA_COLLABORATION_ET_AL__2018 href=...         NaN  4755.00
3  <a refstr=VON_BRAUN_ET_AL__2014 href=https://u...      K0 III  4705.00
4  <a refstr=STASSUN_ET_AL__2019 href=https://ui....         NaN  4675.18

   st_rad  ...  st_logg                                         sy_refname  \
0     NaN  ...      NaN  <a refstr=STASSUN_ET_AL__2019 href=https://ui....
1   13.76  ...     2.45  <a refstr=STASSUN_ET_AL__2019 href=https://ui....
2   17.18  ...      NaN  <a refstr=STASSUN_ET_AL__2019 href=https://ui....
3   15.78  ...      NaN  <a refstr=STASSUN_ET_AL__2019 href=https://ui....
4   17.41  ...      NaN  <a refstr=STASSUN_ET_AL__2019 href=https://ui....

          rastr          ra         decstr        dec  sy_dist  sy_vmag  \
0  12h20m42.91s  185.178779  +17d47m35.71s  17.793252  93.1846  4.72307
1  12h20m42.91s  185.178779  +17d47m35.71s  17.793252  93.1846  4.72307
2  12h20m42.91s  185.178779  +17d47m35.71s  17.793252  93.1846  4.72307
3  12h20m42.91s  185.178779  +17d47m35.71s  17.793252  93.1846  4.72307
4  12h20m42.91s  185.178779  +17d47m35.71s  17.793252  93.1846  4.72307

   sy_kmag  sy_gaiamag
0    2.282     4.44038
1    2.282     4.44038
2    2.282     4.44038
3    2.282     4.44038
4    2.282     4.44038

[5 rows x 23 columns]

In [5]:
planetary_clean = pd.DataFrame(planetary_data[['pl_name',"hostname", "pl_bmasse", "pl_rade", "pl_orbper", "pl_eqt"]])
planetary_clean.head(30)
# Constants
G = 6.67430e-11  # gravitational constant in m^3 kg^-1 s^-2
M_earth = 5.972e24  # mass of Earth in kg
R_earth = 6.371e6  # radius of Earth in m

# Adding gravity calculation to planetary data
planetary_clean = planetary_data[['pl_name',"hostname", "pl_bmasse", "pl_rade", "pl_orbper", "pl_eqt"]].copy()

# Calculate gravity
planetary_clean['gravity'] = G * (planetary_clean['pl_bmasse'] * M_earth) / ((planetary_clean['pl_rade'] * R_earth) ** 2)

# Display
planetary_clean.head(30)

,pl_name,hostname,pl_bmasse,pl_rade,pl_orbper,pl_eqt,gravity
0,11 Com b,11 Com,5434.70000,NaN,NaN,NaN,NaN
1,11 Com b,11 Com,6165.60000,NaN,326.03000,NaN,NaN
2,11 Com b,11 Com,4914.89849,NaN,323.21000,NaN,NaN
3,11 UMi b,11 UMi,4684.81420,NaN,516.21997,NaN,NaN
4,11 UMi b,11 UMi,3432.40000,NaN,NaN,NaN,NaN
5,11 UMi b,11 UMi,3337.07000,NaN,516.22000,NaN,NaN
6,14 And b,14 And,1131.15130,NaN,186.76000,NaN,NaN
7,14 And b,14 And,1017.00000,NaN,NaN,NaN,NaN
8,14 And b,14 And,1525.50000,NaN,185.84000,NaN,NaN
9,14 Her b,14 Her,1474.67000,NaN,1773.40000,NaN,NaN
10,14 Her b,14 Her,1581.13800,NaN,1766.00000,NaN,NaN
11,14 Her b,14 Her,2559.47216,NaN,1765.03890,NaN,NaN
12,14 Her b,14 Her,1481.08780,NaN,1773.40002,NaN,NaN
13,14 Her b,14 Her,1506.45000,NaN,1796.40000,NaN,NaN
14,14 Her b,14 Her,1541.46777,NaN,1766.41000,NaN,NaN
15,14 Her b,14 Her,1554.12000,NaN,1724.00000,NaN,NaN
16,14 Her b,14 Her,1440.66300,NaN,NaN,NaN,NaN
17,16 Cyg B b,16 Cyg B,556.83537,NaN,799.45000,NaN,NaN
18,16 Cyg B b,16 Cyg B,533.95440,NaN,798.50000,NaN,NaN
19,16 Cyg B b,16 Cyg B,476.70000,NaN,800.80000,NaN,NaN
20,16 Cyg B b,16 Cyg B,533.93000,NaN,799.50000,NaN,NaN
21,16 Cyg B b,16 Cyg B,533.93000,NaN,799.50000,NaN,NaN
22,16 Cyg B b,16 Cyg B,565.73740,NaN,798.50000,NaN,NaN
23,17 Sco b,17 Sco,1373.01872,NaN,578.38000,NaN,NaN
24,18 Del b,18 Del,3273.50000,NaN,993.30000,NaN,NaN
25,18 Del b,18 Del,2926.24614,NaN,982.85000,NaN,NaN
26,18 Del b,18 Del,3127.30000,NaN,NaN,NaN,NaN
27,1RXS J160929.1-210524 b,1RXS J160929.1-210524,4000.00000,NaN,NaN,1700.0,NaN
28,1RXS J160929.1-210524 b,1RXS J160929.1-210524,3000.00000,NaN,NaN,1700.0,NaN
29,1RXS J160929.1-210524 b,1RXS J160929.1-210524,3000.00000,NaN,NaN,1800.0,NaN

In [17]:

# Filter the DataFrame using dropna() to keep hostnames and other data
planetary_filtered = planetary_clean.dropna(subset=['pl_bmasse', 'pl_rade', 'pl_orbper', 'pl_eqt', 'gravity'])

print("Null Check: ")
print(planetary_filtered.isnull().sum())  # Checking if it works

print("\nTable: ")
print(planetary_filtered.describe())

Null Check:
pl_name      0
hostname     0
pl_bmasse    0
pl_rade      0
pl_orbper    0
pl_eqt       0
gravity      0
dtype: int64

Table:
         pl_bmasse      pl_rade     pl_orbper       pl_eqt      gravity
count  1519.000000  1519.000000  1.519000e+03  1519.000000  1519.000000
mean    354.006681     9.045301  2.776303e+05  1182.556287    35.199619
std     742.779168     6.019167  1.031835e+07   549.861496   136.422855
min       0.070000     0.310000  1.797150e-01   125.000000     0.409084
25%      10.145000     2.603500  2.720255e+00   718.500000     9.802217
50%     129.034000    10.637000  4.098503e+00  1170.000000    14.975806
75%     365.503585    13.803500  9.209170e+00  1586.500000    26.810989
max    8899.195400    23.539000  4.020000e+08  4050.000000  3745.257070

In [19]:

planetary_final = planetary_filtered.reset_index(drop=True) 
planetary_final.index += 1  

print(planetary_final)

           pl_name      hostname   pl_bmasse  pl_rade  pl_orbper  pl_eqt  \
1         55 Cnc e        55 Cnc     7.81000    2.080   0.736544  1958.0
2         AU Mic b        AU Mic    17.00000    4.070   8.463000   593.0
3         AU Mic c        AU Mic    13.60000    3.240  18.859019   454.0
4      BD+20 594 b     BD+20 594    16.30000    2.230  41.685500   546.0
5     BD-14 3065 b  BD-14 3065 A  3932.00000   21.590   4.288973  2001.0
...            ...           ...         ...      ...        ...     ...
1515        XO-5 b          XO-5   344.52772   12.207   4.187757  1203.0
1516        XO-6 b          XO-6  1398.45200   23.203   3.765001  1577.0
1517        XO-7 b          XO-7   225.34147   15.390   2.864142  1743.0
1518      pi Men c      HD 39091     4.82000    2.042   6.267900  1170.0
1519      pi Men c      HD 39091     4.52000    2.060   6.268340  1147.0

        gravity
1     17.726977
2     10.077909
3     12.722112
4     32.187570
5     82.835889
...         ...
1515  22.704743
1516  25.507600
1517   9.342739
1518  11.351307
1519  10.459581

[1519 rows x 7 columns]

In [21]:
# Merge based on index
merged_atmos_data = pd.concat([atmos_data, atmos_data2], axis=1)

# Remove columns where all values are null
merged_atmos_data = merged_atmos_data.dropna(axis=1, how='all')

# Create a new DataFrame with the needed columns (excluding MINTRANMID and MAXTRANMID)
merged_atmos_data = pd.DataFrame(merged_atmos_data[['pl_name', 'FLAM', 'CENTRALWAVELNG', 
                                                     'MINWAVELNG', 'MAXWAVELNG']])

# Remove rows with any null values and count removed rows
initial_shape = merged_atmos_data.shape[0]
merged_atmos_data.dropna(inplace=True)
removed_count = initial_shape - merged_atmos_data.shape[0]

# Display the number of rows removed and the cleaned DataFrame
print(f"Number of rows removed: {removed_count}")
print("Cleaned Merged Atmospheric Data:")
print(merged_atmos_data.shape)
print(merged_atmos_data)

print(merged_atmos_data)
merged_atmos_planetary = pd.merge(merged_atmos_data, planetary_final, how='inner')
print(merged_atmos_planetary)

averaged_data = merged_atmos_planetary.groupby('pl_name').agg({
    'FLAM': 'mean',
    'CENTRALWAVELNG': 'mean',
    'MINWAVELNG': 'mean',
    'MAXWAVELNG': 'mean',
    'hostname': 'first', 
    'pl_bmasse': 'first',
    'pl_rade': 'first',
    'pl_orbper': 'first',
    'pl_eqt': 'first',
    'gravity': 'first'
}).reset_index()


print(averaged_data)

Number of rows removed: 16576
Cleaned Merged Atmospheric Data:
(858, 5)
                       pl_name          FLAM  CENTRALWAVELNG  MINWAVELNG  \
0    2MASS J12073346-3932539 b  3.798154e-17         0.97011      0.9701
1                     51 Eri b  2.753652e-17         0.97036      1.1141
2                     51 Eri b  2.623155e-17         0.97061      1.0093
3                     51 Eri b  2.867343e-17         0.97085      0.9814
4                     51 Eri b  2.014197e-17         0.97110      1.5890
..                         ...           ...             ...         ...
853                     XO-4 b  2.955499e-17         1.18046      3.6000
854                  bet Pic b  3.511523e-17         1.18070      1.8450
855                  bet Pic b  3.500859e-17         1.18095      1.8450
856                  bet Pic b  3.619541e-17         1.18120      1.9700
857                  bet Pic b  3.730994e-17         1.18144      4.9000

     MAXWAVELNG
0        5.2690
1        1.7974
2        1.6407
3        1.3292
4        2.2550
..          ...
853      4.5000
854      4.4010
855      4.4010
856      2.4900
857      6.8300

[858 rows x 5 columns]
                       pl_name          FLAM  CENTRALWAVELNG  MINWAVELNG  \
0    2MASS J12073346-3932539 b  3.798154e-17         0.97011      0.9701
1                     51 Eri b  2.753652e-17         0.97036      1.1141
2                     51 Eri b  2.623155e-17         0.97061      1.0093
3                     51 Eri b  2.867343e-17         0.97085      0.9814
4                     51 Eri b  2.014197e-17         0.97110      1.5890
..                         ...           ...             ...         ...
853                     XO-4 b  2.955499e-17         1.18046      3.6000
854                  bet Pic b  3.511523e-17         1.18070      1.8450
855                  bet Pic b  3.500859e-17         1.18095      1.8450
856                  bet Pic b  3.619541e-17         1.18120      1.9700
857                  bet Pic b  3.730994e-17         1.18144      4.9000

     MAXWAVELNG
0        5.2690
1        1.7974
2        1.6407
3        1.3292
4        2.2550
..          ...
853      4.5000
854      4.4010
855      4.4010
856      2.4900
857      6.8300

[858 rows x 5 columns]
       pl_name          FLAM  CENTRALWAVELNG  MINWAVELNG  MAXWAVELNG hostname  \
0     55 Cnc e  4.846038e-17         0.97184      4.5000      4.5000   55 Cnc
1     55 Cnc e  3.845097e-17         0.97209      4.5000      4.5000   55 Cnc
2     55 Cnc e  2.316910e-17         0.97233      6.5825     11.4545   55 Cnc
3     55 Cnc e  1.176978e-17         0.97258      3.9650      4.9650   55 Cnc
4     55 Cnc e  1.026221e-17         0.97283      0.4735      0.6560   55 Cnc
...        ...           ...             ...         ...         ...      ...
2113  XO-2 N b  3.403467e-17         1.17972      0.6792      0.8839   XO-2 N
2114    XO-3 b  3.661692e-17         1.17996      4.5000      4.5000     XO-3
2115    XO-3 b  3.218332e-17         1.18021      3.6000      8.0000     XO-3
2116    XO-4 b  2.955499e-17         1.18046      3.6000      4.5000     XO-4
2117    XO-4 b  2.955499e-17         1.18046      3.6000      4.5000     XO-4

       pl_bmasse  pl_rade  pl_orbper  pl_eqt     gravity
0        7.81000    2.080   0.736544  1958.0   17.726977
1        7.81000    2.080   0.736544  1958.0   17.726977
2        7.81000    2.080   0.736544  1958.0   17.726977
3        7.81000    2.080   0.736544  1958.0   17.726977
4        7.81000    2.080   0.736544  1958.0   17.726977
...          ...      ...        ...     ...         ...
2113   188.47319   11.030   2.615864  1328.0   15.212790
2114  3759.92890   13.989   3.191529  1729.0  188.675976
2115  3759.92890   13.989   3.191529  1729.0  188.675976
2116   483.41943   14.460   4.125020  1630.0   22.703762
2117   491.68301   14.426   4.125083  1630.0   23.200837

[2118 rows x 11 columns]
       pl_name          FLAM  CENTRALWAVELNG  MINWAVELNG  MAXWAVELNG hostname  \
0     55 Cnc e  2.387247e-17        0.972703    3.769125    4.589137   55 Cnc
1    CoRoT-1 b  1.928687e-17        0.975044    1.726327    2.234164  CoRoT-1
2    CoRoT-2 b  1.876029e-17        0.976770    3.416667    6.050000  CoRoT-2
3    GJ 1132 b  2.033649e-17        0.978743    2.075600    3.855546  GJ 1132
4    GJ 1214 b  2.323439e-17        0.983305    1.563471    2.390446  GJ 1214
..         ...           ...             ...         ...         ...      ...
153  WASP-98 b  2.736732e-17        1.177500    0.459000    0.898900  WASP-98
154     XO-1 b  3.013663e-17        1.177990    1.977667    3.806667     XO-1
155   XO-2 N b  3.466074e-17        1.179100    1.103883    2.062717   XO-2 N
156     XO-3 b  3.440012e-17        1.180085    4.050000    6.250000     XO-3
157     XO-4 b  2.955499e-17        1.180460    3.600000    4.500000     XO-4

      pl_bmasse  pl_rade  pl_orbper  pl_eqt     gravity
0       7.81000    2.080   0.736544  1958.0   17.726977
1     327.36490   17.385   1.508969  1915.0   10.636360
2    1134.65310   16.365   1.742994  1521.0   41.604604
3       1.62000    1.160   1.628930   409.0   11.822501
4       8.17000    2.742   1.580404   596.0   10.670812
..          ...      ...        ...     ...         ...
153   293.03926   12.823   2.962640  1171.0   17.500757
154   291.76794   13.518   3.941534  1196.0   15.679167
155   179.89178   11.018   2.615857  1319.0   14.551779
156  3759.92890   13.989   3.191529  1729.0  188.675976
157   483.41943   14.460   4.125020  1630.0   22.703762

[158 rows x 11 columns]

In [214]:

stellar_clean = pd.DataFrame(stellar_data[['hostname', 'st_teff', 'st_rad', 'st_mass', 'st_met']])
stellar_clean.dropna()
stellar_clean.drop_duplicates()
stellar_clean.shape

(44974, 5)

In [169]:
stellar_clean = pd.DataFrame(stellar_data[['hostname', 'st_teff', 'st_rad', 'st_mass', 'st_met']])

merged_data = pd.merge(averaged_data, stellar_clean, on='hostname', how='inner')

# Check for missing values in the merged data
print("\nMissing Values in Merged Data:")
print(merged_data.isnull().sum())

# Drop rows with missing values in the merged data
cleaned_data = merged_data.dropna()
print(f"\nData after dropping missing values: {cleaned_data.shape}")

cleaned_data.reset_index(drop=True, inplace=True) 
cleaned_data.index += 1  

# Display the cleaned merged data
print("\nCleaned Merged Data:")
print(cleaned_data)

Missing Values in Merged Data:
pl_name             0
FLAM                0
CENTRALWAVELNG      0
MINWAVELNG          0
MAXWAVELNG          0
hostname            0
pl_bmasse           0
pl_rade             0
pl_orbper           0
pl_eqt              0
gravity             0
st_teff           330
st_rad            346
st_mass           697
st_met            940
dtype: int64

Data after dropping missing values: (921, 15)

Cleaned Merged Data:
      pl_name          FLAM  CENTRALWAVELNG  MINWAVELNG  MAXWAVELNG hostname  \
1    55 Cnc e  2.387247e-17        0.972703    3.769125    4.589137   55 Cnc
2    55 Cnc e  2.387247e-17        0.972703    3.769125    4.589137   55 Cnc
3    55 Cnc e  2.387247e-17        0.972703    3.769125    4.589137   55 Cnc
4    55 Cnc e  2.387247e-17        0.972703    3.769125    4.589137   55 Cnc
5    55 Cnc e  2.387247e-17        0.972703    3.769125    4.589137   55 Cnc
..        ...           ...             ...         ...         ...      ...
917    XO-4 b  2.955499e-17        1.180460    3.600000    4.500000     XO-4
918    XO-4 b  2.955499e-17        1.180460    3.600000    4.500000     XO-4
919    XO-4 b  2.955499e-17        1.180460    3.600000    4.500000     XO-4
920    XO-4 b  2.955499e-17        1.180460    3.600000    4.500000     XO-4
921    XO-4 b  2.955499e-17        1.180460    3.600000    4.500000     XO-4

     pl_bmasse  pl_rade  pl_orbper  pl_eqt    gravity  st_teff  st_rad  \
1      7.81000     2.08   0.736544  1958.0  17.726977   5172.0    0.94
2      7.81000     2.08   0.736544  1958.0  17.726977   5235.0    0.93
3      7.81000     2.08   0.736544  1958.0  17.726977   5172.0    0.95
4      7.81000     2.08   0.736544  1958.0  17.726977   5196.0    0.94
5      7.81000     2.08   0.736544  1958.0  17.726977   5234.0    0.94
..         ...      ...        ...     ...        ...      ...     ...
917  483.41943    14.46   4.125020  1630.0  22.703762   6400.0    1.56
918  483.41943    14.46   4.125020  1630.0  22.703762   5700.0    1.55
919  483.41943    14.46   4.125020  1630.0  22.703762   6397.0    1.53
920  483.41943    14.46   4.125020  1630.0  22.703762   6397.0    1.53
921  483.41943    14.46   4.125020  1630.0  22.703762   6397.0    1.45

     st_mass  st_met
1       0.91    0.35
2       0.96    0.31
3       0.87    0.35
4       0.91    0.31
5       0.91    0.31
..       ...     ...
917     1.32   -0.04
918     1.32   -0.04
919     1.28   -0.04
920     1.28   -0.04
921     1.10   -0.04

[921 rows x 15 columns]

In [173]:
final = merged_data.groupby('pl_name').agg({
    'FLAM': 'first',
    'CENTRALWAVELNG': 'first',
    'MINWAVELNG': 'first',
    'MAXWAVELNG': 'first',
    'hostname': 'first',  # Keep the first hostname
    'pl_bmasse': 'first',
    'pl_rade': 'first',
    'pl_orbper': 'first',
    'pl_eqt': 'first',
    'gravity': 'first',
    'st_teff': 'mean',     # Average stellar temperature
    'st_rad': 'mean',      # Average stellar radius
    'st_mass': 'mean',     # Average stellar mass
    'st_met': 'mean'       # Average stellar metallicity
}).reset_index()

print(final)

       pl_name          FLAM  CENTRALWAVELNG  MINWAVELNG  MAXWAVELNG hostname  \
0     55 Cnc e  2.387247e-17        0.972703    3.769125    4.589137   55 Cnc
1    CoRoT-1 b  1.928687e-17        0.975044    1.726327    2.234164  CoRoT-1
2    CoRoT-2 b  1.876029e-17        0.976770    3.416667    6.050000  CoRoT-2
3    GJ 1132 b  2.033649e-17        0.978743    2.075600    3.855546  GJ 1132
4    GJ 1214 b  2.323439e-17        0.983305    1.563471    2.390446  GJ 1214
..         ...           ...             ...         ...         ...      ...
153  WASP-98 b  2.736732e-17        1.177500    0.459000    0.898900  WASP-98
154     XO-1 b  3.013663e-17        1.177990    1.977667    3.806667     XO-1
155   XO-2 N b  3.466074e-17        1.179100    1.103883    2.062717   XO-2 N
156     XO-3 b  3.440012e-17        1.180085    4.050000    6.250000     XO-3
157     XO-4 b  2.955499e-17        1.180460    3.600000    4.500000     XO-4

      pl_bmasse  pl_rade  pl_orbper  pl_eqt     gravity      st_teff  \
0       7.81000    2.080   0.736544  1958.0   17.726977  5247.824167
1     327.36490   17.385   1.508969  1915.0   10.636360  6078.637778
2    1134.65310   16.365   1.742994  1521.0   41.604604  5567.155833
3       1.62000    1.160   1.628930   409.0   11.822501  3310.518333
4       8.17000    2.742   1.580404   596.0   10.670812  3097.289286
..          ...      ...        ...     ...         ...          ...
153   293.03926   12.823   2.962640  1171.0   17.500757  5504.125000
154   291.76794   13.518   3.941534  1196.0   15.679167  5722.967000
155   179.89178   11.018   2.615857  1319.0   14.551779  5312.992308
156  3759.92890   13.989   3.191529  1729.0  188.675976  6573.142222
157   483.41943   14.460   4.125020  1630.0   22.703762  6303.210000

       st_rad   st_mass    st_met
0    0.948333  0.929333  0.330273
1    1.173750  1.090000 -0.124000
2    0.892222  0.968571 -0.011111
3    0.226667  0.186000 -0.145000
4    0.208462  0.166000  0.145714
..        ...       ...       ...
153  0.720000  0.790000 -0.563333
154  0.933636  0.991250  0.006143
155  1.055455  0.966667  0.410000
156  1.573333  1.206250 -0.126286
157  1.538750  1.265714 -0.037143

[158 rows x 15 columns]

For the above, I have averaged the data that gave multiple readings for the same planet, so essentially, this data, has each unique planet with averaged data for each one, if you want, you can just leave it as the multiple readings, it does inflate the samples I guess.

Now, I will do the same but for the test data, which is the habitable planets data. 
 Arguably, a lot of the indicators but the one in the link didn't provide that of the ESI, so I went to find something else from this link: 

https://www.hpcf.upr.edu/~abel/phl/hwc/data/hwc_table_all.csv

## This is for the Potentially Habitable Ones

In [220]:
# For the test-set

live_worlds = pd.read_csv('habitable_worlds.csv')
worlds_clean = pd.DataFrame(live_worlds[['Name', 'Mass<br>(M<sub>E</sub>)', 'Radius<br>(R<sub>E</sub>)', '<i>T<sub>surf</sub></i><br>(K)', 
                                        'Period<br>(days)', 'Distance<br>(ly)', 'ESI']])
print(worlds_clean)
print("These are all potentially habitable!")

            Name  Mass<br>(M<sub>E</sub>)  Radius<br>(R<sub>E</sub>)  \
0      TOI-904 c                    5.340                      2.167
1      TOI-700 e                    0.818                      0.953
2      TOI-700 d                    1.250                      1.073
3       GJ 357 d                    6.100                      2.340
4      GJ 3293 d                    7.600                      2.670
..           ...                      ...                        ...
65       K2-72 e                    2.210                      1.290
66  Kepler-443 b                    6.040                      2.330
67      K2-332 b                    5.480                      2.200
68    Ross 508 b                    4.000                      1.830
69   Wolf 1069 b                    1.260                      1.080

    <i>T<sub>surf</sub></i><br>(K)  Period<br>(days)  Distance<br>(ly)  \
0                       244.820750         83.999700        150.322365
1                       305.688111         27.809780        101.520947
2                       276.939259         37.423960        101.520947
3                       226.261383         55.661000         30.795030
4                       251.304031         48.134500         65.851875
..                             ...               ...               ...
65                      306.685393         24.158868        216.672280
66                      278.800421        177.669300       2616.655003
67                      298.985869         17.706320        401.830715
68                      301.859146         10.770000         36.563066
69                      258.518058         15.564000         31.256867

         ESI
0   0.658603
1   0.912032
2   0.941176
3   0.575518
4   0.629777
..       ...
65  0.870824
66  0.714604
67  0.729321
68  0.770771
69  0.848593

[70 rows x 7 columns]
These are all potentially habitable!

For the one in total, there is this --- 
Choose at your own discretion

In [223]:
live_worlds_all = pd.read_csv('hwc_all.csv')
clean_all = pd.DataFrame(live_worlds_all[['P_NAME', 'P_MASS', 'P_RADIUS', 'P_PERIOD', 'P_TEMP_EQUIL', 'P_ESI']])
print(clean_all.dropna())

            P_NAME     P_MASS  P_RADIUS     P_PERIOD  P_TEMP_EQUIL     P_ESI
1     Kepler-276 c   16.60000      2.90    31.884000     541.98483  0.272032
2     Kepler-829 b    5.10000      2.11     6.883376    1001.11710  0.254763
3         K2-283 b   12.20000      3.52     1.921036    1104.46820  0.193906
4     Kepler-477 b    4.94000      2.07    11.119907     681.30334  0.276721
5       TOI-1260 c   13.20000      2.76     7.493134     595.75408  0.260440
...            ...        ...       ...          ...           ...       ...
5592    TOI-1694 b   26.10000      5.44     3.770150     954.65289  0.146990
5594   HD 222155 b  581.62598     13.40  3999.000000     150.37253  0.178593
5595    HD 88986 b   17.20000      2.49   146.050000     417.87626  0.379540
5596   Kepler-30 b   11.30000      3.90    29.334340     523.80007  0.241771
5597     HD 3167 d    4.33000      1.92     8.411200     788.76035  0.272975

[5317 rows x 6 columns]